image: 
  name: registry.gitlab.com/dreae/sourcemod-build:latest
  entrypoint: 
  - /bin/bash

build:
  script:
  - /sourcemod/scripting/spcomp -o deadzones src/plugin.sp
  artifacts:
    paths:
      - deadzones.smx